# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"get_apartments": "apt.ipynb",
         "show_apts": "apt.ipynb"}

modules = ["apt.py"]

doc_url = "https://hamelsmu.github.io/getapt/"

git_url = "https://github.com/hamelsmu/getapt/tree/master/"

def custom_doc_links(name): return None
